spring:
  application:
    name: catalog-service

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pcbuilder_catalog}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  address: 0.0.0.0
  port: ${PORT:8080}