spring:
  application:
    name: build-service

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${BUILD_DB_URL:jdbc:postgresql://localhost:5432/pcbuilder_builds}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  catalog-service:
    url: ${CATALOG_SERVICE_URL:http://localhost:8080}

  compatibility-service:
    url: ${COMPATIBILITY_SERVICE_URL:http://localhost:8081}

server:
  address: 0.0.0.0
  port: ${PORT:8082}